import argparse
from pathlib import Path

import cv2


def main() -> None:
    parser = argparse.ArgumentParser(description="Preview an overlay image generated by pipeline.py.")
    parser.add_argument("image")
    parser.add_argument("--output", default="outputs/preview.png")
    args = parser.parse_args()

    image = cv2.imread(args.image)
    if image is None:
        raise SystemExit(f"Cannot read image: {args.image}")
    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    cv2.imwrite(args.output, image)
    print(f"saved: {args.output}")


if __name__ == "__main__":
    main()
